"""added a user model

Revision ID: 54210d4d1342
Revises: 726cf4b980af
Create Date: 2024-11-05 15:07:20.422227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54210d4d1342'
down_revision: Union[str, None] = '726cf4b980af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todoitems_todolist_id_fkey', 'todoitems', type_='foreignkey')
    op.create_foreign_key(None, 'todoitems', 'todolist', ['todolist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todoitems', type_='foreignkey')
    op.create_foreign_key('todoitems_todolist_id_fkey', 'todoitems', 'todolist', ['todolist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
